### ISSUE TITLE
owncloud log throws a log when browsing to User Authentication menu in settings

### ISSUE THREAD

**Issue by davitol** [owncloud/impersonate#117]
Tested with oC 10.0.10.RC3 adn Impersonate 0.2.0

```
{"reqId":"IiAWygwmHWz662cbzq7W","level":3,"time":"2018-09-14T09:58:00+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=authentication","message":"json_decode() expects parameter 1 to be string, array given at \/mnt\/data\/apps\/impersonate\/templates\/settings-admin.php#17"}
```
![screen shot 2018-09-14 at 12 02 49](https://user-images.githubusercontent.com/10596560/45543958-41f27480-b816-11e8-9b6c-441580537373.png)

**Comment by PVince81** [comment]
From Sentry:
```
ErrorException: json_decode() expects parameter 1 to be string, array given
#14 impersonate/templates/settings-admin.php(17): handleError
#13 sentry/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): json_decode
#12 impersonate/templates/settings-admin.php(17): include
#11 /var/www/owncloud/lib/private/Template/Base.php(219): load
#10 /var/www/owncloud/lib/private/Template/Base.php(194): fetchPage
#9 /var/www/owncloud/lib/private/legacy/template.php(236): fetchPage
#8 /var/www/owncloud/settings/Controller/SettingsPageController.php(171): getPanelsData
#7 /var/www/owncloud/settings/Controller/SettingsPageController.php(104): getAdmin
#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(153): executeController
#5 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(85): dispatch
#4 /var/www/owncloud/lib/private/AppFramework/App.php(100): main
#3 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): __invoke
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(909): handleRequest
#0 /var/www/owncloud/index.php(54): null
```

What are the steps to reproduce ? Just open the section ? @davitol

**Comment by davitol** [comment]
Yes, that is the only thing done:

```
cc app:list
Enabled:
  - activity: 2.3.7
  - admin_audit: 1.0.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - customgroups: 0.3.6
  - dav: 0.4.0
  - encryption: 1.3.1
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.6.0
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - guests: 0.5.0
  - impersonate: 0.2.0
  - market: 0.2.5
  - notifications: 0.3.5
  - objectstore: 0.5
  - provisioning_api: 0.5.0
  - ransomware_protection: 1.0.3
  - sentry: 0.0.1
  - sharepoint: 0.1.4
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - theme-enterprise: 2.0.2
  - twofactor_totp: 0.4.4
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0
  - user_shibboleth: 3.2.0
  - windows_network_drive: 0.7.1
  - workflow: 0.2.6
Disabled:
  - external
  - files_ldap_home
  - user_external
```
