### ISSUE TITLE
Subadmin cannot impersonate users from its group

### ISSUE THREAD

**Issue by davitol** [owncloud/impersonate#118]
### Steps to reproduce

1 - As admin create a group 'group1' add three members 'user1', 'user2', 'user3'
2 - Make 'user1' group admin of 'group1'
3 - Login as 'user2' and log out
4 - Login as 'user1'
5 - Go to the users view.
6 - Impersonate 'user2'.

### Expected behaviour

 User1 should be able to impersonate user2

### Actual behavior

User2 cannot be impersonated

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.0.10RC3

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No
**Logs**

```
{"reqId":"1qw3GK1Qhj3WbmntWMK4","level":3,"time":"2018-09-14T12:09:20+00:00","remoteAddr":"172.18.0.1","user":"user1","app":"index","method":"POST","url":"\/apps\/impersonate\/user","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function inGroup() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Impersonate\\\\Controller\\\\SettingsController->impersonate('user2')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Impersonate\\\\Controller\\\\SettingsController), 'impersonate')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Impersonate\\\\Controller\\\\SettingsController), 'impersonate')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Impersonate...', 'impersonate', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/impersona...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/mnt\\\/data\\\/apps\\\/impersonate\\\/controller\\\/settingscontroller.php\",\"Line\":174}"}
```

### Client configuration

**browser**

Firefox

**Comment by sharidas** [comment]
Looking into it.

**Comment by PVince81** [comment]
Not reproducible. The env in question had an additional group "guest_app" and the error was due to the "guest_app" group not existing any more after disabling guest app.

**Comment by patrickjahns** [comment]
More defensive checking here https://github.com/owncloud/impersonate/pull/119
