### ISSUE TITLE
Impersonate a non logged in user causes exception

### ISSUE THREAD

**Issue by sharidas** [owncloud/impersonate#17]
*Steps to produce*

1)On a scratch installed OC, create two users: user1 and user2
2)Login as user1( which is the admin user ).
3) Enable impersonate app
4) Go to users page and try to impersonate user : "user2" ( Remember user2 wasn't logged in till the time or its as equivalent as first login via impersonate )
5) The exception occurs and the page navigation stops. Hence user2 home page is not seen.

Below is the exception got from the owncloud.log:
`{"reqId":"PsZzLM6jU5uOVJrSu6bQ","level":3,"time":"2017-04-13T05:13:09+00:00","remoteAddr":"127.0.0.1","user":"bar","app":"index","method":"GET","url":"\/testing\/index.php\/apps\/files","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(135): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(206): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/apps\\\/files')\\n#10 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":570}"}`

**Comment by PVince81** [comment]
This is likely because of the slightly hacky approach we use for impersonating users.

Now I even wonder whether we should change it to use the proper login code.

The way how the user is replaced in the session bypasses any pre/post login hooks and also bypasses skeleton folder creation for the first login.

The latter (skeleton folder creation missing) is what is causing this error.

To research: public API methods to logout and login users "officially"

**Comment by PVince81** [comment]
@butonic not sure whether you researched that in the past before using the `setUser()` hack

**Comment by butonic** [comment]
In the end the login code changes the userId the same way as impersonate does. The login hooks are used to properly initialize the encryption. I had a look at how ownBrander does impersonation before carving out the logic into the impersonate app.  user_shibboleth 'logs in' a user because it implements an apache auth backend. IIRC I could not use any public API to log in a user with only his userid. Which is why I kept the hack. Remember the app was written ... urgently back in the days with @msrex asking for it.

I agree that we should be less hacky about logging in the user. Post 10.0

**Comment by butonic** [comment]
Also, after a page refresh the user is logged in and can upload files. Only copying the skeleton does not work.

**Comment by PVince81** [comment]
We might still need to find a way to fix the skeleton issue then. It is legitimate for an admin to want to impersonate a newly created user maybe to setup their homes and shares initially.

**Comment by PVince81** [comment]
> Also, after a page refresh the user is logged in and can upload files. Only copying the skeleton does not work.

Ok, then maybe a JS hack would do... triggering the first failing call with ajax and then logging in or so.

**Comment by PVince81** [comment]
I tried this but refreshing the page did not solve the issue. I had to kill the cookies to get a usable OC again.

**Comment by PVince81** [comment]
We could try to call this logic: https://github.com/owncloud/core/blob/v10.0.0beta2/lib/private/User/Session.php#L469 and maybe also trigger the hooks and update the "last login timestamp" manually. This is important to make sure the "initial login" hook is only ever called once.

Calling `prepareUserLogin($firstTimeLogin)` will trigger skeleton creation.

**Comment by PVince81** [comment]
Or add a public method 'switchToUser` in IUserSession ? This way it could still run all the relevant private code...

**Comment by sharidas** [comment]
Small test conducted. I modified the access controller of  method prepareUserLogin in Session.php to public. And then called it in the settings controller of impersonate app. Basically tried to call prepareUserLogin(true) before the setUser. I have verified that the call progress to the modified method. Below is the log obtained in the owncloud.log:
`{"reqId":"9RkeD3ITSHDi1HxJgYx5","level":2,"time":"2017-04-24T09:11:45+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"impersonate","method":"POST","url":"\/testing\/index.php\/apps\/impersonate\/user","message":"User admin trying to impersonate user user1"}
{"reqId":"9RkeD3ITSHDi1HxJgYx5","level":2,"time":"2017-04-24T09:11:45+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"impersonate","method":"POST","url":"\/testing\/index.php\/apps\/impersonate\/user","message":"changing to user user1"}
{"reqId":"XDJfvRwgIFxkkbajkNRB","level":3,"time":"2017-04-24T09:12:50+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"index","method":"GET","url":"\/testing\/index.php\/apps\/files","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(135): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(206): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/apps\\\/files')\\n#10 \\\/home\\\/sujith\\\/test\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/sujith\\\/test\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":570}"}
`

**Comment by sharidas** [comment]
Ok so my previous investigation didn't worked out. But made a bit more progress and figured out that the following changes after setUser in the SettingsController of impersonate app:
`
			\OC::$server->getSession()->set('loginname', $userid);
			$firstTimeLogin = $user->updateLastLoginTimestamp();
			$this->userSession->prepareUserLogin($firstTimeLogin);`

Removes the exception. So eventually the only change in the core I did till now is modifying access specifier of prepareUserLogin to public.

**Comment by sharidas** [comment]
This is one change which I made as a followup: https://gist.github.com/sharidas/4e99a76dc4f2d9e558468590408b1ce1 and need to do further testing. I did test with a couple of users and didn't failed.

**Comment by sharidas** [comment]
https://gist.github.com/sharidas/4e99a76dc4f2d9e558468590408b1ce1/revisions#diff-39859e34161f0cb6f5f50974282a2593R20 line if removed, user will face the exception.

**Comment by PVince81** [comment]
For the first version of this app, let's detect this situation beforehand and display a proper error message for the admin.

You can detect whether a user has never logged in with the "lastlogin" property of the user (spelling might be different)

**Comment by PVince81** [comment]
This PR adds a friendly error message early: https://github.com/owncloud/impersonate/issues/27

Keeping ticket open for the proper fix.
